# Copyright 2025 Altaira Labs
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# This is a manually created stub matching the proto definition.
# Run `python -m grpc_tools.protoc` to regenerate from runtime.proto.

"""gRPC client and server classes for omnia.runtime.v1.RuntimeService."""

import grpc

from omnia_langchain_runtime import runtime_pb2


class RuntimeServiceStub:
    """Client stub for RuntimeService."""

    def __init__(self, channel: grpc.Channel):
        """Initialize the stub.

        Args:
            channel: gRPC channel to use.
        """
        self.Converse = channel.stream_stream(
            "/omnia.runtime.v1.RuntimeService/Converse",
            request_serializer=lambda x: x.SerializeToString(),
            response_deserializer=runtime_pb2.ServerMessage.FromString,
        )
        self.Health = channel.unary_unary(
            "/omnia.runtime.v1.RuntimeService/Health",
            request_serializer=lambda x: x.SerializeToString(),
            response_deserializer=runtime_pb2.HealthResponse.FromString,
        )


class RuntimeServiceServicer:
    """Server interface for RuntimeService."""

    async def Converse(self, request_iterator, context):
        """Handle bidirectional streaming conversation.

        Args:
            request_iterator: Iterator of ClientMessage.
            context: gRPC context.

        Yields:
            ServerMessage responses.
        """
        raise NotImplementedError("Method not implemented!")

    async def Health(self, request, context):
        """Health check.

        Args:
            request: HealthRequest.
            context: gRPC context.

        Returns:
            HealthResponse.
        """
        raise NotImplementedError("Method not implemented!")


def add_RuntimeServiceServicer_to_server(servicer, server):
    """Add RuntimeServiceServicer to a gRPC server.

    Args:
        servicer: RuntimeServiceServicer implementation.
        server: gRPC server to add to.
    """
    rpc_method_handlers = {
        "Converse": grpc.stream_stream_rpc_method_handler(
            servicer.Converse,
            request_deserializer=lambda x: _deserialize_client_message(x),
            response_serializer=lambda x: _serialize_server_message(x),
        ),
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=lambda x: runtime_pb2.HealthRequest(),
            response_serializer=lambda x: _serialize_health_response(x),
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "omnia.runtime.v1.RuntimeService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


def _deserialize_client_message(data: bytes) -> runtime_pb2.ClientMessage:
    """Deserialize ClientMessage from bytes.

    Note: This is a stub. In production, use protobuf-generated code.
    """
    # For stub purposes, return empty message
    # Real implementation would parse protobuf bytes
    return runtime_pb2.ClientMessage()


def _serialize_server_message(msg: runtime_pb2.ServerMessage) -> bytes:
    """Serialize ServerMessage to bytes.

    Note: This is a stub. In production, use protobuf-generated code.
    """
    # For stub purposes, return empty bytes
    # Real implementation would serialize to protobuf
    return b""


def _serialize_health_response(msg: runtime_pb2.HealthResponse) -> bytes:
    """Serialize HealthResponse to bytes."""
    return b""
