# Copyright 2025 Altaira Labs
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# This is a manually created stub matching the proto definition.
# Run `python -m grpc_tools.protoc` to regenerate from runtime.proto.

"""Protocol buffer messages for omnia.runtime.v1."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()


class ClientMessage(_message.Message):
    """Message from client to runtime."""

    DESCRIPTOR = None  # Will be set by protoc

    def __init__(
        self,
        session_id: str = "",
        content: str = "",
        metadata: dict | None = None,
        parts: list | None = None,
    ):
        self.session_id = session_id
        self.content = content
        self.metadata = metadata or {}
        self.parts = parts or []


class ServerMessage(_message.Message):
    """Message from runtime to client."""

    DESCRIPTOR = None

    def __init__(
        self,
        chunk: "Chunk | None" = None,
        tool_call: "ToolCall | None" = None,
        tool_result: "ToolResult | None" = None,
        done: "Done | None" = None,
        error: "Error | None" = None,
    ):
        self.chunk = chunk
        self.tool_call = tool_call
        self.tool_result = tool_result
        self.done = done
        self.error = error

    def HasField(self, field_name: str) -> bool:
        """Check if a oneof field is set."""
        return getattr(self, field_name, None) is not None

    def WhichOneof(self, oneof_name: str) -> str | None:
        """Return which oneof field is set."""
        if oneof_name == "message":
            for field in ["chunk", "tool_call", "tool_result", "done", "error"]:
                if getattr(self, field, None) is not None:
                    return field
        return None


class Chunk(_message.Message):
    """Text chunk for streaming."""

    DESCRIPTOR = None

    def __init__(self, content: str = ""):
        self.content = content


class ToolCall(_message.Message):
    """Tool invocation notification."""

    DESCRIPTOR = None

    def __init__(
        self,
        id: str = "",
        name: str = "",
        arguments_json: str = "",
    ):
        self.id = id
        self.name = name
        self.arguments_json = arguments_json


class ToolResult(_message.Message):
    """Tool execution result."""

    DESCRIPTOR = None

    def __init__(
        self,
        id: str = "",
        result_json: str = "",
        is_error: bool = False,
    ):
        self.id = id
        self.result_json = result_json
        self.is_error = is_error


class Done(_message.Message):
    """Completion signal."""

    DESCRIPTOR = None

    def __init__(
        self,
        final_content: str = "",
        usage: "Usage | None" = None,
        parts: list | None = None,
    ):
        self.final_content = final_content
        self.usage = usage
        self.parts = parts or []


class ContentPart(_message.Message):
    """Multimodal content part."""

    DESCRIPTOR = None

    def __init__(
        self,
        type: str = "",
        text: str = "",
        media: "MediaContent | None" = None,
    ):
        self.type = type
        self.text = text
        self.media = media


class MediaContent(_message.Message):
    """Media content (image, audio, video)."""

    DESCRIPTOR = None

    def __init__(
        self,
        data: str = "",
        url: str = "",
        mime_type: str = "",
    ):
        self.data = data
        self.url = url
        self.mime_type = mime_type


class Usage(_message.Message):
    """Token usage statistics."""

    DESCRIPTOR = None

    def __init__(
        self,
        input_tokens: int = 0,
        output_tokens: int = 0,
        cost_usd: float = 0.0,
    ):
        self.input_tokens = input_tokens
        self.output_tokens = output_tokens
        self.cost_usd = cost_usd


class Error(_message.Message):
    """Error message."""

    DESCRIPTOR = None

    def __init__(
        self,
        code: str = "",
        message: str = "",
    ):
        self.code = code
        self.message = message


class HealthRequest(_message.Message):
    """Health check request."""

    DESCRIPTOR = None

    def __init__(self):
        pass


class HealthResponse(_message.Message):
    """Health check response."""

    DESCRIPTOR = None

    def __init__(
        self,
        healthy: bool = False,
        status: str = "",
    ):
        self.healthy = healthy
        self.status = status
